version: '3'
services:
  reviews:
    image: meekoder/reviews:latest
    depends_on:
      - 'database'
    ports: 
      - '3004:3004'

  database:
    image: mongo:latest

  sizepicker:
    image: kwongandy/sizepicker:latest
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'

  trackpinch:
    image: gregoryrichens/trackpinch:latest
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  suggestions:
    image: ameyeoh/suggestions:latest
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  reviewsproxy:
    image: meekoder/proxy:latest
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'
